import type { DB, Service, CoverageZone, Booking, Review, BlackoutDate } from "./types";
import { addDays, toISO, todayISO } from "./format";

const services: Service[] = [
  {
    id: "cut-skin-fade",
    name: "Signature Skin Fade",
    category: "Cuts",
    description: "Clipper-to-skin fade with a sharp line and a clean neck finish.",
    minutes: 45,
    price: 30000,
    active: true,
  },
  {
    id: "cut-taper-fade",
    name: "Taper Fade ",
    category: "Cuts",
    description: "Short taper through the sides and back, hair left fuller on top.",
    minutes: 40,
    price: 30000,
    active: true,
  },
  {
    id: "cut-low-cut",
    name: "MOHAWK",
    category: "Cuts",
    description: "Sharp sides, bold strip down the middle, hairline and edges shaped by clipper.",
    minutes: 30,
    price: 30000,
    active: true,
  },
  {
    id: "cut-afro-trim",
    name: "MID-FADE",
    category: "Cuts",
    description: "Afro levelled and shaped without losing the length you grew.",
    minutes: 35,
    price: 30000,
    active: true,
  },
  {
    id: "kids-fade",
    name: "Kids Fade",
    category: "Kids",
    description: "For ages 12 and under. Quick, gentle and no crying.",
    minutes: 30,
    price: 30000,
    active: true,
  },
  {
    id: "kids-cut-line",
    name: "",
    category: "Kids",
    description: "",
    minutes: 30,
    price: 0,
    active: true,
  },
  {
    id: "extra-towel",
    name: "Hot Towel Treatment",
    category: "Extras",
    description: "Steam towel, scalp rub and a cold rinse. Good after a rough week.",
    minutes: 15,
    price: 2000,
    active: true,
  },
  {
    id: "extra-dye",
    name: "",
    category: "Extras",
    description: "",
    minutes: 30,
    price: 0,
    active: true,
  },
];

/**
 * Nine travel zones. `feeMin`/`feeMax` are the starting call-out range for the
 * trip and `customerShare` is the slice the customer pays. Fresco absorbs the rest.
 */
const zones: CoverageZone[] = [
  {
    id: "zone-1",
    name: "Zone 1",
    areas: ["Ogba", "Ikeja", "Agege", "Ijaiye", "Oregun", "Opebi", "Alausa"],
    feeMin: 5000,
    feeMax: 5000,
    customerShare: 0.5,
    active: true,
  },
  {
    id: "zone-2",
    name: "Zone 2",
    areas: ["Berger", "Magodo", "Ketu", "Ojota", "Maryland", "Anthony"],
    feeMin: 6000,
    feeMax: 9000,
    customerShare: 0.5,
    active: true,
  },
  {
    id: "zone-3",
    name: "Zone 3",
    areas: ["Gbagada", "Yaba", "Surulere", "Shomolu", "Oshodi", "Mushin"],
    feeMin: 9000,
    feeMax: 13000,
    customerShare: 0.5,
    active: true,
  },
  {
    id: "zone-4",
    name: "Zone 4",
    areas: ["Ebute Metta", "Oyingbo", "Apapa", "Ijora"],
    feeMin: 12000,
    feeMax: 17000,
    customerShare: 0.5,
    active: true,
  },
  {
    id: "zone-5",
    name: "Zone 5",
    areas: ["Festac", "Mile 2", "Amuwo", "Satellite", "Ojo"],
    feeMin: 16000,
    feeMax: 21000,
    customerShare: 0.6,
    active: true,
  },
  {
    id: "zone-6",
    name: "Zone 6",
    areas: ["Lagos Island", "Marina", "Victoria Island", "Ikoyi", "Oniru"],
    feeMin: 16000,
    feeMax: 19000,
    customerShare: 0.7,
    active: true,
  },
  {
    id: "zone-7",
    name: "Zone 7",
    areas: ["Lekki", "Lekki Phase 1", "Ajah", "Chevron", "VGC"],
    feeMin: 19000,
    feeMax: 25000,
    customerShare: 0.7,
    active: true,
  },
  {
    id: "zone-8",
    name: "Zone 8",
    areas: ["Sangotedo", "Lakowe", "Ibeju-Lekki", "Eleko", "Akodo"],
    feeMin: 25000,
    feeMax: null,
    customerShare: 0.8,
    active: true,
  },
  {
    id: "zone-9",
    name: "Zone 9",
    areas: ["Ikorodu and surrounding areas"],
    feeMin: 18000,
    feeMax: 23000,
    customerShare: 0.5,
    active: true,
  },
];

const reviews: Review[] = [
  {
    id: "rev-1",
    firstName: "Chidi",
    area: "Lekki Phase 1",
    quote: "He came at 7pm after work, set up in the dining room and my fade was sharper than the one I pay for in the salon.",
    rating: 5,
    date: toISO(addDays(new Date(), -8)),
  },
  {
    id: "rev-2",
    firstName: "Tunde",
    area: "Ikoyi",
    quote: "Clippers were cleaned in front of me and he brought his own cape, mirror and everything. No stress.",
    rating: 5,
    date: toISO(addDays(new Date(), -15)),
  },
  {
    id: "rev-3",
    firstName: "Ifeanyi",
    area: "Surulere",
    quote: "Booked in the morning, he was at my door before 4pm. Cut and line-up in one sitting, money well spent.",
    rating: 5,
    date: toISO(addDays(new Date(), -22)),
  },
  {
    id: "rev-4",
    firstName: "Ayo",
    area: "Yaba",
    quote: "My two boys get their hair cut at home now. He is patient with them and it's cleaner than taking them out.",
    rating: 5,
    date: toISO(addDays(new Date(), -30)),
  },
  {
    id: "rev-5",
    firstName: "Kelechi",
    area: "Ajah",
    quote: "He gave me fair prices and confirmed it on WhatsApp before coming, so there was no surprise at the end.",
    rating: 4,
    date: toISO(addDays(new Date(), -41)),
  },
  {
    id: "rev-6",
    firstName: "Seyi",
    area: "Ikeja GRA",
    quote: "Same barber every time, so he already knows how I like the line-up. That is why I stopped going to a shop.",
    rating: 5,
    date: toISO(addDays(new Date(), -55)),
  },
];

function offsetDays(days: number): string {
  return toISO(addDays(new Date(), days));
}

const bookings: Booking[] = [
  {
    id: "bk-seed-1",
    name: "Chidi Okonkwo",
    phone: "0803 555 1122",
    serviceId: "cut-skin-fade",
    addOnIds: [],
    date: todayISO(),
    slot: "10:00 am",
    address: "12 Admiralty Way, Flat 3",
    area: "Zone 7",
    landmark: "Beside Ebeano supermarket",
    clients: 1,
    notes: "Buzzer is not working, please call when you reach the gate.",
    status: "confirmed",
    createdAt: offsetDays(-1),
  },
  {
    id: "bk-seed-2",
    name: "Tunde Bakare",
    phone: "0806 421 7788",
    serviceId: "cut-skin-fade",
    addOnIds: ["extra-towel"],
    date: todayISO(),
    slot: "12:00 pm",
    address: "4 Bourdillon Road, Apartment 9",
    area: "Zone 6",
    landmark: "White gate after the filling station",
    clients: 1,
    notes: "",
    status: "confirmed",
    createdAt: offsetDays(-2),
  },
  {
    id: "bk-seed-3",
    name: "Ifeanyi Eze",
    phone: "0812 330 9911",
    serviceId: "cut-taper-fade",
    addOnIds: [],
    date: todayISO(),
    slot: "6:00 pm",
    address: "27 Ogunlana Drive",
    area: "Zone 3",
    landmark: "Opposite the pink building",
    clients: 1,
    notes: "Please come through the back gate.",
    status: "new",
    createdAt: todayISO(),
  },
  {
    id: "bk-seed-4",
    name: "Ayo Adeyemi",
    phone: "0809 774 2200",
    serviceId: "kids-fade",
    addOnIds: [],
    date: offsetDays(1),
    slot: "10:00 am",
    address: "8 Herbert Macaulay Way",
    area: "Zone 3",
    landmark: "Yellow block, second floor",
    clients: 2,
    notes: "Two boys, 9 and 6. Please bring two capes.",
    status: "new",
    createdAt: offsetDays(-1),
  },
  {
    id: "bk-seed-5",
    name: "Kelechi Nwosu",
    phone: "0705 118 6633",
    serviceId: "cut-low-cut",
    addOnIds: ["extra-towel"],
    date: offsetDays(1),
    slot: "4:00 pm",
    address: "15 Abraham Adesanya Estate, Block C",
    area: "Zone 7",
    landmark: "Close to the estate mosque",
    clients: 1,
    notes: "",
    status: "confirmed",
    createdAt: offsetDays(-2),
  },
  {
    id: "bk-seed-6",
    name: "Seyi Ogunleye",
    phone: "0802 664 3321",
    serviceId: "cut-afro-trim",
    addOnIds: [],
    date: offsetDays(2),
    slot: "12:00 pm",
    address: "31 Isaac John Street, Ikeja GRA",
    area: "Zone 1",
    landmark: "Blue gate, ask for Mr Seyi",
    clients: 1,
    notes: "Grooming for a wedding on Saturday.",
    status: "new",
    createdAt: offsetDays(-1),
  },
  {
    id: "bk-seed-7",
    name: "Emeka Uche",
    phone: "0815 909 4477",
    serviceId: "cut-afro-trim",
    addOnIds: [],
    date: offsetDays(-1),
    slot: "6:00 pm",
    address: "9 Oniru Market Road",
    area: "Zone 6",
    landmark: "Beside the pharmacy",
    clients: 1,
    notes: "",
    status: "done",
    createdAt: offsetDays(-3),
  },
  {
    id: "bk-seed-8",
    name: "Bimbo Aliyu",
    phone: "0807 233 5510",
    serviceId: "kids-fade",
    addOnIds: [],
    date: offsetDays(-2),
    slot: "2:00 pm",
    address: "44 Bode Thomas Street",
    area: "Zone 3",
    landmark: "Green house at the end of the close",
    clients: 1,
    notes: "",
    status: "done",
    createdAt: offsetDays(-4),
  },
];

const blackouts: BlackoutDate[] = [
  { date: offsetDays(7), reason: "Family day" },
  { date: offsetDays(21), reason: "Restocking clippers and blades" },
];

export const defaultDB: DB = {
  services,
  bookings,
  zones,
  blackouts,
  reviews,
  settings: {
    businessName: "Fresco Hairvolution",
    phone: "0704 302 7379",
    whatsapp: "2347043027379",
    instagram: "fresco_hairvolution",
    tiktok: "fresco_hairvolution",
    heroHeadline: "Sharp cuts. At your door.",
    heroSubline:
      "Fresco comes to your home with the clippers, the cape and sterilised tools. Fades and kids' cuts across Lagos, seven days a week.",
    calloutNote:
      "Fresco splits the travel cost with you. Zones 1 to 4 and Ikorodu are 50/50, Zone 5 is 60/40, Zones 6 and 7 are 70/30, and Zone 8 is 80/20. You pay your share of the call-out for your zone, he carries the rest, and the figure is confirmed on WhatsApp before he leaves.",
    includedLine:
      "Fresco brings clippers and guards, sterilising spray, a cape and neck strip, comb, razor, mirror and a brush. You only need a chair, a socket and water to rinse.",
    ownerPin: "2468",
    hours: [
      { open: "10:00", close: "18:00", closed: false },
      { open: "08:00", close: "20:00", closed: false },
      { open: "08:00", close: "20:00", closed: false },
      { open: "08:00", close: "20:00", closed: false },
      { open: "08:00", close: "20:00", closed: false },
      { open: "08:00", close: "21:00", closed: false },
      { open: "08:00", close: "21:00", closed: false },
    ],
  },
};
